# res://scripts/units/UnitShared.gd
class_name UnitShared

enum ActionMode {
	FREE,
	COLLECT_STARTING,
	COLLECTING,
	COLLECT_STOPPING,
	BUILD_STARTING,
	BUILDING,
	BUILD_STOPPING,
	UNDER_CONSTRUCTION,
	CONDUIT
}
